services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=root
      - CORS_ALLOWED_ORIGINS=http://frontend:5173,http://localhost:5173
      - DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    tty: true
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    tty: true

volumes:
  postgres_data: